### ISSUE TITLE
NullAssignment Issue (Not found varNodes & fieldNodes)

### ISSUE THREAD

**Issue by dailyco** [HGUISEL/FPCollector#22]
[ Project beam ]

1. 실제로 violated 된 line에 변수가 없는 경우 (1)
ex) return Objects.hash(DummySink.class,
          getTempDirectoryProvider().isAccessible() ? getTempDirectoryProvider().get() : null);

2. violated된 line에 있는 변수가 해당 파일 내에 field나 변수로 declaration 된 적이 없는 경우 (2)
ex) dynamicSplitResultToReport = null; (dynamicSplitResultToReport 변수가 해당 파일 내에 declaration된 적 없음)

3. Lazily initialized (9)
ex) void function() { this.cachedFiredTimers = null; }
          ...
    // Lazily initialized
    private Iterator<TimerData> cachedFiredTimers = null;

4. 한 개는 모르겠음... (1)
- 프로젝트 위치 : /Users/yujin/ISEL/NewProject/FPCollector/git/beam/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/Flatten.java
- line : 130 ~ 130 (주석 제외... 이야기 해봐야 할듯)

[ Project isis ]
None

**Comment by dailyco** [comment]
Lazily initialized 같은 경우
declaration 을 먼저 돌려서 리스트에 넣고 violated var을 구하는건 어떨지...

**Comment by testation21** [comment]
Case 1(num. 26, 167(Case 4)). 
pmd error(not confirmed): No Variables or fields -> No Assignment occurs.

Case 2
Fixed.

When I fixed second case, Other Problems were solved together.
